

# services:
#   web:
#     build: ./resort-rental-backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./resort-rental-backend/:/usr/src/resort-rental-backend/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev

version: '3.8'

services:
  web:
    build: "E:/Resort Rental Fullstack App (Airbnb Clone)/resort-rental-backend"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "E:/Resort Rental Fullstack App (Airbnb Clone)/resort-rental-backend/:/usr/src/resort-rental-backend/"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
